### ISSUE TITLE
SearchPartyVisualFindNext doesnt update the search register

### ISSUE THREAD

**Issue by junkmechanic** [dahu/SearchParty#10]
Hi Bary,
VisualFindNext does not update the search register. The result is that to continue searching for the selected term, one would have to press `<leader>*` successively. Not that that is a huge issue. In fact in this case, `n` extends the selection till the next occurrence (which might be desirable) which conforms to vim's default functionality.

**But** a side effect is that the selected text cannot be searched for in other opened buffers.

Do you want to consider letting the user choose to : `exit visual mode, update "/ and jump to the next occurrence` (only on calling SearchPartyVisualFindNext ; `n` retains default behavior otherwise) over the current functionality.

**Comment by dahu** [comment]
You can access the visual match as a search pattern by pressing `<Up>` from within the search prompt.
Is that sufficient for your needs?

**Comment by junkmechanic** [comment]
Oh. Didnt realize that was a possibility. I can work with that.

However, I dont use the default behavior as often as I intend to search the selected text. So is it sufficient? Yes. Optimal? No.  :laughing: 

Are you completely opposed to this idea?

**Comment by dahu** [comment]
Ok. I just added another option to control this (on the user_maps branch)

let searchparty_visual_find_sets_search = 1

**Comment by junkmechanic** [comment]
Just one small thing. What I had in mind was this :
```
  if search(term, flags)
    if g:searchparty_visual_find_sets_search
      let @/ = term
    else
      silent! exe 'normal! ' . visualmode() . '/' . term . "/e\<cr>"
    endif
  endif
```

so I could fire away `n` like there's no tomorrow.

**Comment by dahu** [comment]
No. The point of the visual find is to stay in visual mode.
Currently, you use `*` to find the next visual selection match. To find the subsequent one, press `*` again.
With the new `g:searchparty_visual_find_sets_search`, the search register will be updated too, allowing the use of `n` once you exit out of visual mode.

**Comment by junkmechanic** [comment]
Fair enough.

If I may, what kind of use case warrants staying in visual mode while successively searching for the same pattern. Because if one intends to act upon the visual selection, it is bound to exit visual mode. And if one doesnt intend to do anything with the selection, then it might as well exit visual mode.
In my experience the reason for visual search is to be able to search for selections that are not standard text objects.

What kind of use cases am I missing?

**Comment by junkmechanic** [comment]
Small edit:

You missed `g:` for the sets_search variable in the README.

**Comment by dahu** [comment]
When done from the `~/.vimrc`, `g:` isn't necessary

**Comment by dahu** [comment]
Pull the *user_maps* branch again. Change your `~/.vimrc` line to:
`let searchparty_visual_find_sets_search = 2`

**Comment by junkmechanic** [comment]
splendido!
