### ISSUE TITLE
Clearing highlight on resetting TAHW

### ISSUE THREAD

**Issue by junkmechanic** [dahu/SearchParty#11]
In `autoload/searchparty/search_highlights.vim`
```
function! searchparty#search_highlights#toggle_AHCW()
  if exists('#SearchPartyTAHW')
    augroup SearchPartyTAHW
      au!
    augroup END
    augroup! SearchPartyTAHW
    call feedkeys("\<Plug>SearchPartyHighlightClear")
  else
    augroup SearchPartyTAHW
      au! CursorHold * call feedkeys("\<Plug>SearchPartyHighlightWord")
    augroup END
  endif
endfunction
```
One line included right before `else`.
Currently, the highlight on all the occurrences of the previously highlighted word persist even on turning AHCW off.

Side note : fixed indentation.

**Comment by dahu** [comment]
Is wanting to turn off the auto-highlighter the same as wanting to clear the current highlight?
I had left them as separate actions. I don't mind clearing highlight here (as you have presented it). If people complain, I'll add an option.

**Comment by junkmechanic** [comment]
Yes, I see your point. Someone might want the last highlight to persist (while being able to move the cursor around). But for that you have `SearchPartyHighlightWord`.

Thanks for including the change.
The addition of `<silent>` is a welcome change too. :D

**Comment by dahu** [comment]
You're welcome
