### ISSUE TITLE
Disables mapping for <C-l>

### ISSUE THREAD

**Issue by marcopolo4k** [dahu/SearchParty#13]
This plugin interferes with one navigation mapping I have, making a shortcut key to go to the next-right window:
```
nnoremap <C-l> <C-w>l
```

I've disabled everything else in my ~/.vimrc, and yet this problem can be reproduced:

1. Open a file (buffer)
2. Open a vertical split buffer `:vs` (2nd buffer)
3. Navigate back to first buffer
4. Use the SearchParty plugin's search: visually select a word, then search for it: `ve*`
5. Escape out of the plugin's mode, try to use the mapping <C l> to get to the right window - 2nd buffer
6. It does nothing - the mapping no longer works, you're stuck on buffer 1
7. Try moving the cursor around, or searching for a different word by normal means like `/`.  It's still broken.
8. Workaround: reload the config file (`:source ~/.vimrc`) or else quit out of vim and restart it.  This fixes the issue, and you have your navigation mapping back.

I see the same behavior on several versions of vim and operating systems:

- vim 8.0.1763 - AlmaLinux 8, Rocky Linux 8, Cloudlinux 8
- vim 8.1.3741 - Ubuntu 20
- vim 8.2.3370 - CentOS 7
- vim 9.0.472 - macOS 12.6.2

Update: I found another factor: junegunn/vim-plug

**Comment by dahu** [comment]
In Vim's normal default configuration, the `<c-l>` key clears the visual highlight. (`:help :redraw` and look at the entry above it in the `various.txt` help file.) SearchParty piggybacks on this default by calling it first and then calling SearchParty's <Plug>SearchPartyHighlightClear (which also clears any current MASH highlights).
SearchParty's key maps are defined in `searchparty_user_maps.vim` in SearchParty's root directory. You can change the `<c-l>` map there to another key combo of your choice.

**Comment by marcopolo4k** [comment]
Thank you! I understand and must admit this was not a bug at all.

**Comment by dahu** [comment]
You're welcome. No problem. Happy searching! :-)
