### ISSUE TITLE
<leader>mm: more bindings

### ISSUE THREAD

**Issue by orbisvicis** [dahu/SearchParty#4]
It isn't worth using this functionality if a (long) command has to be typed afterwards. Suggestions:

* `<leader>MM`: clear all matches
* `<leader>mM`: Prompt for match to clear. All candidates successfully fuzzy-matched against this are cleared
* `<leader>Mm`: all instances of nearest (linewise, from cursor) match are cleared

**Comment by dahu** [comment]
I don't understand... What "long command" has to be typed afterwards for clearing matches?
The <leader>md command shows you the current matches with their associated index and prompts you for an index number to clear.

**Comment by dahu** [comment]
Bah... github ate my markup... The command to clear matches is:

    <leader>md
