### ISSUE TITLE
Option to (or not to) use the default mappings

### ISSUE THREAD

**Issue by junkmechanic** [dahu/SearchParty#9]
Hi,
The plugin has a lot of great mappings, or rather `<Plug>`s. However, I have found 2 issues with the default mappings:
  1. I might want to use different keys for a particular `<Plug>`.

    This is easy to solve as I can just define my own maps for such `<Plug>`s.

  2. I dont want to have a particular set of keys (that SearchParty uses) assigned to anything.
      
    Although I can add a bunch of `<nop>`s for every key combination that I want unmapped from one of SearchParty `<Plug>`s. But there has got to be a more elegant solution. 

Is it possible to add a flag that could indicate if the user would like to use the default mappings.
Alternately, suggestion for mappings can be made without actually doing the mappings.

**Comment by dahu** [comment]
The shadow maps (extending vim's existing normal mode commands (/, ?, *, g*, #, g#, n, N)) are not as easy to make user-choosable, but all of the others are easily customisable. I'll put a solution up soon.

**Comment by dahu** [comment]
Try the new user_maps branch

**Comment by junkmechanic** [comment]
Hi Bary,
Thanks for the effort. This is is exactly what I had hoped for. Works as you ha

**Comment by dahu** [comment]
You're welcome.

**Comment by junkmechanic** [comment]
Do you plan to merge this branch with master?

**Comment by dahu** [comment]
I do, yes. I thought I'd let it sit for a bit first; see if any bugs pop up.

**Comment by junkmechanic** [comment]
Hi Bary,
I came across an issue. I can no longer see the result of indexed-search on performing search (using shadow maps or SearchPartyHighlightWord), the status line displays the following :
```
:let @/='\<'.expand('<cword>').'\>'\set hlsearch
```


Also as a side note, `<Plug>SearchPartyVisualFIndNext / Previous` do not yield to indexed-search even in the master branch. Let me know if it could be an issue with my setup.

**Comment by dahu** [comment]
I think the second problem is to do with being in (and re-entering) visual mode.
I can't reproduce the first problem. :-/

**Comment by dahu** [comment]
I just merged user_maps into master
